version: '3'

services:
  database:
    image: postgres
    container_name: database
    security_opt:
      - seccomp:unconfined
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data


  adressbuchsbackend:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: adressbuchsbackend
    security_opt:
      - seccomp:unconfined
    depends_on:
      - database
    ports:
      - 8082:8082
    volumes:
      - ./target/adressbuchs-0.0.1-SNAPSHOT.jar adressbuchs.jar
    #    command: ["java", "-jar", "educombackend.jar"]
    networks:
       - educomNetwork
    links:
      - database

volumes:
  database-data:
networks:
  educomNetwork:


